"use client";
import {useEffect,useRef,useState} from "react";
import {MapPin,Moon,Sun,RotateCcw,Plus,Minus,Play,Pause,ArrowUpRight,Layers3,ShieldCheck,ParkingCircle,Wallet,ChevronRight,Route,Move3D,Contrast} from "lucide-react";
import {Tabs,TabsList,TabsTrigger,TabsContent} from "@/components/ui/tabs";
import {Switch} from "@/components/ui/switch";
import {Slider} from "@/components/ui/slider";
import Campus,{type CampusHandle,type Space,initialSpaces} from "./scene";
const sectors=[{id:"A",name:"Setor A",detail:"Lateral oeste · bloco A"},{id:"B",name:"Setor B",detail:"Lateral leste · bloco B"},{id:"V",name:"Visitantes",detail:"Acesso principal"}];
const plans=[{name:"Mensal",months:1,price:120},{name:"Bimestral",months:2,price:220},{name:"Semestral",months:6,price:600}];
const money=(v:number)=>v.toLocaleString("pt-BR",{style:"currency",currency:"BRL",maximumFractionDigits:0});
export default function Home(){
const [night,setNight]=useState(false),[playing,setPlaying]=useState(true),[tour,setTour]=useState(false),[route,setRoute]=useState(false),[colorblind,setColorblind]=useState(false),[view,setView]=useState("vagas"),[selected,setSelected]=useState(""),[space,setSpace]=useState<string|null>(null),[spaces,setSpaces]=useState<Space[]>(initialSpaces),[days,setDays]=useState(20),[plan,setPlan]=useState(0),[event,setEvent]=useState("Simulação iniciada · 42 vagas livres");
const scene=useRef<CampusHandle|null>(null);const free=spaces.filter(s=>!s.occupied).length;
const choose=(id:string)=>{setSelected(id);setSpace(null);setTour(false);scene.current?.focus(id);};
useEffect(()=>{const d=document as Document & {modelContext?:{registerTool:(t:unknown,o:unknown)=>Promise<void>}};if(!d.modelContext)return;const controller=new AbortController();d.modelContext.registerTool({name:"configure_campus_view",description:"Configura dia ou noite e o setor da maquete simulada.",inputSchema:{type:"object",properties:{night:{type:"boolean"},sector:{type:"string",enum:["A","B","V",""]}},required:["night","sector"],additionalProperties:false},execute:async(input:unknown)=>{const i=input as {night:boolean;sector:string};if(typeof i.night!=="boolean"||!["A","B","V",""].includes(i.sector))throw new Error("Configuração inválida");setNight(i.night);choose(i.sector);await new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)));return{night:i.night,sector:i.sector,simulated:true};}},{signal:controller.signal}).catch(()=>{});return()=>controller.abort();},[]);
const current=spaces.find(s=>s.id===space);
return <main className={`parking-app ${night?"night":""} ${colorblind?"colorblind-mode":""}`.trim()}>
<header className="topbar"><a className="brand" href="/" aria-label="UDF Parking início"><span className="brand-mark">P<span>•</span></span><div><strong>UDF<span> PARKING</span></strong><small>SEU CAMPUS, MAIS PERTO.</small></div></a><div className="campus-address"><MapPin size={16}/><span>Campus Sede <b>·</b> Brasília, DF</span></div><span className="prototype-badge">PROTÓTIPO INTERATIVO</span></header>
<section className="workspace"><div className="map-area"><div className="map-heading"><span className="eyebrow">EXPLORE O CAMPUS</span><h1>Seu próximo destino.<br/><span>Sem procurar uma vaga.</span></h1><p>Selecione um setor e conheça as possibilidades.</p></div>
<Campus onTraffic={(id,occupied,message)=>{if(occupied!==null)setSpaces(prev=>prev.map(s=>s.id===id?{...s,occupied}:s));setEvent(`${id} · ${message}`);}} ref={scene} night={night} playing={playing} tour={tour} route={route} colorblind={colorblind} spaces={spaces} selected={selected} onSpace={s=>{setSpace(s.id);setSelected(s.sector);setView("vagas");setTour(false);}}/>
<div className="map-mode"><Layers3 size={17}/><span>Maquete 3D</span><span className="mode-separator"/><button onClick={()=>setNight(!night)} aria-label={night?"Ativar modo diurno":"Ativar modo noturno"}>{night?<Moon size={17}/>:<Sun size={17}/>} {night?"Noite":"Dia"}</button><span className="mode-separator"/><button className={colorblind?"active":""} onClick={()=>setColorblind(!colorblind)} aria-pressed={colorblind} aria-label={colorblind?"Desativar modo daltônico":"Ativar modo daltônico"}><Contrast size={17}/> Daltônico</button></div>
<div className="camera-controls"><button aria-label="Aproximar câmera" onClick={()=>scene.current?.zoom(.8)}><Plus/></button><button aria-label="Afastar câmera" onClick={()=>scene.current?.zoom(1.25)}><Minus/></button><span/><button aria-label="Restaurar vista geral" onClick={()=>choose("")}><RotateCcw size={19}/></button><button className={tour?"active":""} aria-label={tour?"Parar passeio da câmera":"Iniciar passeio da câmera"} onClick={()=>{setTour(!tour);setSelected("");scene.current?.focus("");}}><Move3D size={20}/></button></div>
<div className="map-bottom"><div className="legend"><span><i className="green"/>Livre</span><span><i className="red"/>Ocupada</span><span><i className="blue"/>Acessível*</span></div><span className="drag-hint">Arraste para girar · role para aproximar</span></div><div className="compass"><span>N</span><i>↑</i></div></div>
<aside className="information"><Tabs value={view} onValueChange={v=>{setView(v);if(v==="seguranca"){setNight(true);setRoute(true);}}}>
<TabsList className="main-tabs"><TabsTrigger value="vagas"><ParkingCircle/>Vagas</TabsTrigger><TabsTrigger value="planos"><Wallet/>Planos</TabsTrigger><TabsTrigger value="seguranca"><ShieldCheck/>Segurança</TabsTrigger></TabsList>
<TabsContent value="vagas" className="panel-content"><div className="panel-title"><h2>Estacionamento</h2><span className="sim-label">SIMULAÇÃO</span></div><div className="availability"><div className="availability-number">{free}<span>/ 72</span></div><p>vagas disponíveis</p><div className="capacity-bar"><i style={{width:`${(72-free)/72*100}%`}}/></div><div className="capacity-label"><span>{72-free} ocupadas</span><span>{Math.round((72-free)/72*100)}% de ocupação</span></div></div>
<div className="section-label">ONDE VOCÊ QUER ESTACIONAR?</div><div className="sector-list">{sectors.map(s=>{const n=spaces.filter(p=>p.sector===s.id&&!p.occupied).length;return <button key={s.id} className={`sector ${selected===s.id?"selected":""}`} onClick={()=>choose(selected===s.id?"":s.id)} aria-pressed={selected===s.id}><span className="sector-icon">{s.id}</span><span className="sector-name"><b>{s.name}</b><small>{s.detail}</small></span><span className="sector-count"><b>{n}</b><small>livres</small></span><ChevronRight size={16}/></button>})}</div>
{current&&<div className="space-detail" role="status"><b>Vaga {current.id}</b><span>{current.occupied?"Ocupada":"Livre"}{current.accessible?" · Acessível":""}</span><small>Consulta demonstrativa. Não reserva a vaga.</small></div>}
{selected&&<div className="slot-picker" aria-label="Vagas do setor selecionado">{spaces.filter(s=>s.sector===selected).map(s=><button key={s.id} aria-label={`${s.id}: ${s.occupied?"ocupada":"livre"}${s.accessible?", acessível":""}`} className={`${s.occupied?"occupied":"free"} ${s.accessible?"accessible":""} ${space===s.id?"chosen":""}`} onClick={()=>setSpace(s.id)}>{s.id.split("-")[1]}</button>)}</div>}
<div className="night-callout"><Moon size={21}/><div><b>Sua volta também importa.</b><p>Conheça os benefícios noturnos.</p><button onClick={()=>{setView("seguranca");setNight(true);setRoute(true);}}>Explorar segurança <ArrowUpRight size={15}/></button></div></div><div className="simulation"><button aria-label={playing?"Pausar simulação":"Retomar simulação"} onClick={()=>setPlaying(!playing)}>{playing?<Pause size={15}/>:<Play size={15}/>}</button><div><b>{playing?"Movimento simulado":"Simulação pausada"}</b><small>{event}</small></div></div></TabsContent>
<TabsContent value="planos" className="panel-content"><span className="eyebrow">MAIS DIAS. MENOS CUSTO.</span><h2>Um plano para sua rotina.</h2><p className="muted">Compare as alternativas à diária de {money(15)}.</p><div className="days-label"><label id="days-label">Dias de uso por mês</label><strong>{days}</strong></div><Slider aria-labelledby="days-label" value={[days]} min={1} max={26} step={1} onValueChange={v=>setDays(v[0])}/><div className="plans">{plans.map((p,i)=><button key={p.name} className={`plan ${plan===i?"selected":""}`} onClick={()=>setPlan(i)} aria-pressed={plan===i}><span><b>{p.name}</b><small>{money(p.price/p.months)} / mês equivalente</small></span><strong>{money(p.price)}<small>por {p.months===1?"mês":`${p.months} meses`}</small></strong></button>)}</div><div className="savings"><span>{days*15*plans[plan].months-plans[plan].price>=0?"Economia estimada no período":"Custo adicional sobre as diárias"}</span><strong>{money(Math.abs(days*15*plans[plan].months-plans[plan].price))}</strong><small>Diárias: {money(days*15*plans[plan].months)} · {days*plans[plan].months} dias de uso</small></div><p className="disclaimer">Valores ilustrativos do Figma. Planos propostos, sem contratação ou cobrança.</p></TabsContent>
<TabsContent value="seguranca" className="panel-content"><span className="eyebrow">CUIDADO NO CAMINHO</span><h2>Uma volta mais próxima.</h2><p className="muted">Propostas para reduzir os trajetos externos de homens e mulheres à noite.</p><div className="benefit emphasis"><ShieldCheck/><span className="sim-label">PROPOSTA</span><h3>Isenção noturna<br/>para mulheres.</h3><p>Incentivo ao uso do estacionamento próximo à faculdade, com isenção da taxa no período noturno.</p></div><div className="benefit"><Moon/><h3>Desconto noturno<br/>para estudantes.</h3><p>Condições diferenciadas para quem frequenta as aulas à noite.</p></div><div className="route-switch"><div><Route size={20}/><label htmlFor="route">Mostrar percurso ilustrativo</label></div><Switch id="route" checked={route} onCheckedChange={setRoute}/></div><p className="disclaimer">Benefícios sujeitos à análise e aprovação da UDF. Percurso e iluminação ilustrativos; não representam uma rota de segurança validada.</p></TabsContent>
</Tabs></aside></section><footer><span><i/> UDF PARKING LAB <b>·</b> Projeto acadêmico</span><span>Campus aproximado · ocupação simulada · *vagas acessíveis podem estar ocupadas</span><a href="https://www.figma.com/design/8sZfS0XjwaMhVcZYGXSvJT/UDF-PARKING" target="_blank" rel="noreferrer">Ver Figma <ArrowUpRight size={14}/></a></footer></main>;
}
