"use client";
import {forwardRef,useEffect,useImperativeHandle,useRef,useState} from "react";
import * as THREE from "three";
import {OrbitControls} from "three/addons/controls/OrbitControls.js";
import {SoftwareRenderer} from "./software-renderer";
export type Space={id:string;sector:string;x:number;z:number;occupied:boolean;accessible:boolean;rotation:number};
export const initialSpaces:Space[]=["A","B","V"].flatMap((sector,si)=>Array.from({length:24},(_,i)=>({id:`${sector}-${String(i+1).padStart(2,"0")}`,sector,x:si===0?-30+(i%2)*7:si===1?23+(i%2)*7:-19+(i%12)*3.45,z:si<2?-24+Math.floor(i/2)*4.1:27+Math.floor(i/12)*8,occupied:i>=[18,16,8][si],accessible:i<2,rotation:si<2?Math.PI/2:0})));
export type CampusHandle={focus:(s:string)=>void;zoom:(f:number)=>void};
type Props={night:boolean;playing:boolean;tour:boolean;route:boolean;spaces:Space[];selected:string;onSpace:(s:Space)=>void};
const Campus=forwardRef<CampusHandle,Props>(function Campus(props,ref){
const host=useRef<HTMLDivElement>(null),state=useRef(props),api=useRef<CampusHandle|null>(null);state.current=props;
const [error,setError]=useState(false),[ready,setReady]=useState(false);
useImperativeHandle(ref,()=>({focus:s=>api.current?.focus(s),zoom:f=>api.current?.zoom(f)}),[]);
useEffect(()=>{if(!host.current)return;const el=host.current;let renderer:THREE.WebGLRenderer;let software=false;try{renderer=new THREE.WebGLRenderer({antialias:true,alpha:true});}catch{renderer=new SoftwareRenderer() as unknown as THREE.WebGLRenderer;software=true;}
renderer.setPixelRatio(Math.min(devicePixelRatio,1.7));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.setClearColor(0x000000,0);renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.25;el.appendChild(renderer.domElement);renderer.domElement.setAttribute("aria-label","Maquete 3D interativa do campus UDF");renderer.domElement.tabIndex=0;
const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(38,1,.1,600);camera.position.set(102,108,130);
const controls=new OrbitControls(camera,renderer.domElement);controls.target.set(0,0,1);controls.enableDamping=true;controls.dampingFactor=.06;controls.minDistance=38;controls.maxDistance=220;controls.maxPolarAngle=Math.PI/2.18;controls.minPolarAngle=.15;controls.enablePan=false;controls.autoRotateSpeed=.55;
const hemi=new THREE.HemisphereLight(0xe8f2ff,0x507157,2.6);scene.add(hemi);const sun=new THREE.DirectionalLight(0xfff4de,3.4);sun.position.set(-35,80,30);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);Object.assign(sun.shadow.camera,{left:-65,right:65,top:65,bottom:-65,near:1,far:200});sun.shadow.bias=-.0005;scene.add(sun);
const mats:THREE.Material[]=[],geos:THREE.BufferGeometry[]=[],textures:THREE.Texture[]=[];
const mat=(c:THREE.ColorRepresentation,opts:THREE.MeshStandardMaterialParameters={})=>{const m=new THREE.MeshStandardMaterial({color:c,roughness:.75,...opts});mats.push(m);return m;};
const white=mat(0xe8edf1),navy=mat(0x203853),glass=mat(0x486982,{metalness:.35,roughness:.25}),roof=mat(0xb4c2ce),concrete=mat(0xc7cfd0),asphalt=mat(0x3f4b56),grass=mat(0x749581),red=mat(0xd7193f),trunk=mat(0x796b57),leaf=mat(0x388574),leaf2=mat(0x4e9981),rubber=mat(0x18212b),lamp=mat(0xffedb2,{emissive:0xffd484,emissiveIntensity:0});
const box=(w:number,h:number,d:number,m:THREE.Material,x:number,y:number,z:number,parent:THREE.Object3D=scene)=>{const g=new THREE.BoxGeometry(w,h,d,Math.max(1,Math.ceil(w/5)),1,Math.max(1,Math.ceil(d/5)));geos.push(g);const a=new THREE.Mesh(g,m);a.position.set(x,y,z);a.castShadow=true;a.receiveShadow=true;parent.add(a);return a;};
const cylinder=(r:number,h:number,m:THREE.Material,x:number,y:number,z:number,parent:THREE.Object3D=scene)=>{const g=new THREE.CylinderGeometry(r,r,h,10);geos.push(g);const a=new THREE.Mesh(g,m);a.position.set(x,y,z);a.castShadow=true;parent.add(a);return a;};
const label=(text:string,x:number,y:number,z:number,color="#203853",scale=10)=>{const c=document.createElement("canvas");c.width=512;c.height=128;const ctx=c.getContext("2d")!;ctx.fillStyle="rgba(255,255,255,.95)";ctx.beginPath();ctx.roundRect(4,4,504,120,20);ctx.fill();ctx.fillStyle=color;ctx.font="bold 48px Arial";ctx.textAlign="center";ctx.textBaseline="middle";ctx.fillText(text,256,66);const tx=new THREE.CanvasTexture(c);textures.push(tx);const m=new THREE.SpriteMaterial({map:tx,depthTest:false});mats.push(m);const s=new THREE.Sprite(m);s.position.set(x,y,z);s.scale.set(scale,scale/4,1);scene.add(s);return s;};
box(88,2,92,white,0,-1.5,0);box(86,.5,90,grass,0,-.3,0);box(81,.25,85,asphalt,0,.05,0);box(69,.3,72,concrete,0,.22,-1);box(39,.3,50,grass,0,.42,-7);
for(const x of [-10,10]){box(10,8,36,white,x,4.6,-8);box(10.8,.6,37,roof,x,8.9,-8);box(10.1,1.1,36.1,navy,x,1.7,-8);for(let z=-23;z<=6;z+=3.2)for(const side of [-1,1])for(const y of [3.5,6.2])box(.12,1.5,2,glass,x+side*5.05,y,z);for(let z=-20;z<4;z+=4)box(7,.12,2.9,glass,x,9.25,z);}
box(32,11,12,white,0,6,-26);box(33,.7,13,roof,0,11.9,-26);box(32.2,2.2,.2,glass,0,8,-19.9);box(32.2,1,.2,red,0,4.2,-19.7);box(7,3,.5,glass,0,2,-19.5);box(6,.3,7,white,0,3.8,-16.5);label("UDF",0,15,-26,"#d7193f",9);
box(7,.12,34,concrete,0,.7,-1);for(let z=-11;z<12;z+=5){box(2.2,.55,.6,navy,-4,.8,z);box(2.2,.55,.6,navy,4,.8,z);}
for(let i=0;i<40;i++){const side=i%2?-1:1,x=i<24?side*37:side*(4+(i%3)*5),z=i<24?-35+Math.floor(i/2)*6.4:13+(Math.floor((i-24)/6)*4);cylinder(.27,2.5,trunk,x,1.6,z);const g=new THREE.IcosahedronGeometry(1.8+(i%3)*.22,1);geos.push(g);const a=new THREE.Mesh(g,i%3?leaf:leaf2);a.position.set(x,3.5,z);a.scale.y=1.15;a.castShadow=true;scene.add(a);}
for(const x of [-41,41])for(let z=-38;z<40;z+=7)box(.18,.05,3,white,x,.25,z);for(let x=-35;x<36;x+=7)box(3,.05,.18,white,x,.25,41);
const car=(color:number)=>{const group=new THREE.Group(),m=mat(color,{metalness:.25,roughness:.35});box(1.75,.65,3.3,m,0,.75,0,group);box(1.55,.7,1.65,glass,0,1.25,-.1,group);box(1.6,.16,1.3,m,0,1.65,-.2,group);for(const x of [-.88,.88])for(const z of [-1,1]){const w=cylinder(.35,.19,rubber,0,0,0,group);w.rotation.z=Math.PI/2;w.position.set(x,.55,z);}box(1.3,.16,.05,lamp,0,.85,1.68,group);scene.add(group);return group;};
const hits:THREE.Object3D[]=[],tiles:THREE.Mesh[]=[],cars:THREE.Group[]=[];initialSpaces.forEach((s,i)=>{const m=mat(0x29b68b,{emissive:0x0c563b,emissiveIntensity:.15}),tile=box(2.85,.09,5.9,m,s.x,.5,s.z);tile.rotation.y=s.rotation;tile.userData.index=i;hits.push(tile);tiles.push(tile);const c=car([0xe7e8ed,0xcedae5,0x263953,0xcc3655,0x75a8b8][i%5]);c.position.set(s.x,.5,s.z);c.rotation.y=s.rotation;c.traverse(o=>{o.userData.index=i;});hits.push(c);cars.push(c);});
label("A · BLOCO A",-28,5,-30,"#d7193f",12);label("B · BLOCO B",28,5,-30,"#d7193f",12);label("VISITANTES",0,4,39,"#d7193f",13);label("VIA W5 SUL",-43,1,0,"#526079",12);label("VIA W4 SUL",43,1,0,"#526079",12);
const routeGroup=new THREE.Group();scene.add(routeGroup);const routeMat=mat(0xffd16d,{emissive:0xffbc38,emissiveIntensity:1.3});for(let z=23;z>-17;z-=1.7)box(.48,.1,.9,routeMat,0,.86,z,routeGroup);for(let x=-19;x<0;x+=1.7)box(.9,.1,.48,routeMat,x,.86,23,routeGroup);
const lights:THREE.PointLight[]=[];for(const x of [-18,18])for(const z of [-28,-10,10,20]){cylinder(.12,4,navy,x,2.4,z);box(1.2,.2,.8,lamp,x,4.5,z);const l=new THREE.PointLight(0xffd78a,0,18,1.6);l.position.set(x,4.1,z);scene.add(l);lights.push(l);}
const mover=car(0xd7193f),mover2=car(0xf5f5ed);let motion=0,targetPos:THREE.Vector3|null=null,targetLook:THREE.Vector3|null=null;
api.current={focus:s=>{const x=s==="A"?-24:s==="B"?24:0,z=s==="V"?26:0;targetLook=new THREE.Vector3(x,0,z);targetPos=s?new THREE.Vector3(x+42,64,z+64):new THREE.Vector3(102,108,130);},zoom:f=>{camera.position.sub(controls.target).multiplyScalar(f).add(controls.target);controls.update();}};controls.addEventListener("start",()=>{targetPos=null;targetLook=null;});
const resize=()=>{const w=el.clientWidth,h=el.clientHeight;renderer.setSize(w,h);camera.aspect=w/h;camera.updateProjectionMatrix();};const observer=new ResizeObserver(resize);observer.observe(el);resize();
const ray=new THREE.Raycaster(),pointer=new THREE.Vector2();let down={x:0,y:0};const pd=(e:PointerEvent)=>{down={x:e.clientX,y:e.clientY};};const pu=(e:PointerEvent)=>{if(Math.hypot(e.clientX-down.x,e.clientY-down.y)>6)return;const r=renderer.domElement.getBoundingClientRect();pointer.set((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1);ray.setFromCamera(pointer,camera);const h=ray.intersectObjects(hits,true).find(h=>h.object.parent?.visible!==false&&h.object.visible);if(h)state.current.onSpace(state.current.spaces[h.object.userData.index]);};renderer.domElement.addEventListener("pointerdown",pd);renderer.domElement.addEventListener("pointerup",pu);
let frame=0,last=0,lastDraw=0;const reduced=matchMedia("(prefers-reduced-motion: reduce)").matches;
const render=(time:number)=>{const dt=Math.min((time-last)/1000,.05);last=time;const p=state.current;hemi.intensity=THREE.MathUtils.lerp(hemi.intensity,p.night?.6:2.6,.04);sun.intensity=THREE.MathUtils.lerp(sun.intensity,p.night?.3:3.4,.04);lamp.emissiveIntensity=p.night?3:0;lights.forEach(l=>{l.intensity=p.night?35:0;});routeGroup.visible=p.route;routeMat.emissiveIntensity=1.1+Math.sin(time*.002)*.3;
tiles.forEach((t,i)=>{const s=p.spaces[i],m=t.material as THREE.MeshStandardMaterial;m.color.setHex(s.occupied?0xcb6671:s.accessible?0x5498ec:0x35b88d);m.emissive.setHex(s.occupied?0x501725:s.accessible?0x163b83:0x085b40);m.emissiveIntensity=p.night?.6:.12;m.opacity=p.selected&&p.selected!==s.sector?.38:1;m.transparent=true;cars[i].visible=s.occupied;});
if(p.playing&&!reduced)motion+=dt*5;[mover,mover2].forEach((c,i)=>{const d=(motion+i*130)%324;if(d<80){c.position.set(-41,.3,-40+d);c.rotation.y=0;}else if(d<162){c.position.set(-41+d-80,.3,40);c.rotation.y=Math.PI/2;}else if(d<242){c.position.set(41,.3,40-(d-162));c.rotation.y=Math.PI;}else{c.position.set(41-(d-242),.3,-40);c.rotation.y=-Math.PI/2;}});
if(targetPos&&targetLook){camera.position.lerp(targetPos,reduced?1:.06);controls.target.lerp(targetLook,reduced?1:.06);if(camera.position.distanceTo(targetPos)<.08){targetPos=null;targetLook=null;}}controls.autoRotate=p.tour&&!reduced;controls.update(dt);if(!software||time-lastDraw>45){renderer.render(scene,camera);lastDraw=time;}frame=requestAnimationFrame(render);};frame=requestAnimationFrame(render);setReady(true);
const loss=(e:Event)=>{e.preventDefault();setError(true);};renderer.domElement.addEventListener("webglcontextlost",loss);
return()=>{cancelAnimationFrame(frame);observer.disconnect();controls.dispose();renderer.dispose();geos.forEach(g=>g.dispose());mats.forEach(m=>m.dispose());textures.forEach(t=>t.dispose());renderer.domElement.remove();api.current=null;};},[]);
return <div className="scene-host" ref={host}>{!ready&&!error&&<div className="scene-message">Preparando o campus 3D…</div>}{error&&<div className="scene-message">Seu navegador não conseguiu abrir o 3D.<br/>Você ainda pode explorar vagas e planos no painel.</div>}</div>;
});export default Campus;
